name: ghcjs-hspec-json
version: "0.1"
description: generically create tests to make sure aeson instances and
  serialization through 'JSVal' agree on JSON formats
synopsis: generic tests for aeson and 'JSVal'
category: Web, Development
maintainer: SoenkeHahn@gmail.com
license: BSD3
license-file: LICENSE

github: soenkehahn/ghcjs-hspec-json

dependencies:
      - base < 5
      - hspec
      - aeson
      - QuickCheck
      - ghcjs-base
      - string-conversions
      - bytestring

ghc-options: >
  -Wall -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates
  -fno-warn-name-shadowing

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
