name: ghcjs-hspec-jsval-aeson
version: "0.1"

dependencies:
      - base < 5
      - hspec
      - aeson
      - QuickCheck
      - ghcjs-base
      - string-conversions
      - bytestring

ghc-options:
  -Wall -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
