name: ghcjs-hspec-jsval-aeson
version: "0.1"

dependencies:
  - base < 5

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
